In [3]:
# Artificial Neural Network
# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

In [30]:
# Part 1 - Data Preprocessing
# Importing the dataset
dataset = pd.read_csv("C:/Users/4nm20/Desktop/134_138/normalized_output.csv")

X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(np.isnan(X).any())
print(y)
print(np.isnan(y).any())

[[6.03417399e-05 1.00000000e+00 3.12197607e-01]
 [6.95018345e-05 5.48813363e-01 3.13973385e-01]
 [5.96706951e-05 3.88594448e-01 3.17788900e-01]
 ...
 [3.85682554e-05 6.86652493e-02 1.09622127e-04]
 [3.79554529e-05 6.86143861e-02 1.31548372e-03]
 [1.27424613e-04 6.86143861e-02 0.00000000e+00]]
False
[0. 0. 0. ... 2. 2. 2.]
False


In [31]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 ... 2 2 2]


In [32]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [33]:
print(X_train, y_train)

[[1.32674059e-04 7.51757322e-02 2.05417699e-01]
 [1.45147646e-04 7.51401280e-02 2.01102310e-01]
 [6.70331047e-01 7.97300184e-02 1.85546086e-01]
 ...
 [5.41124016e-05 7.67474034e-02 2.24445895e-01]
 [6.49953619e-05 8.10300805e-02 8.77627509e-01]
 [1.41889977e-04 7.63557572e-02 4.50875189e-01]] [1 1 2 ... 1 0 1]


In [34]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
# Part 2 - Building the ANN
# Initializing the ANN
ann = tf.keras.models.Sequential()
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.5))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# # Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# # Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dropout(0.5))
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

In [60]:
from tensorflow.keras.utils import to_categorical

y_train_encoded = to_categorical(y_train, num_classes=3)
print(y_train)
print(y_train_encoded)

[1 1 2 ... 1 0 1]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [61]:
ann.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [63]:
history=ann.fit(X_train, y_train_encoded, batch_size = 64, epochs = 40)

Epoch 1/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7583 - accuracy: 0.5942
Epoch 2/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7680 - accuracy: 0.5892
Epoch 3/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7579 - accuracy: 0.5888
Epoch 4/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7509 - accuracy: 0.5920
Epoch 5/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7518 - accuracy: 0.5916
Epoch 6/40
161/161 [==============================] - 1s 3ms/step - loss: 0.7506 - accuracy: 0.5937
Epoch 7/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7515 - accuracy: 0.5927
Epoch 8/40
161/161 [==============================] - 1s 3ms/step - loss: 0.7467 - accuracy: 0.5965
Epoch 9/40
161/161 [==============================] - 1s 4ms/step - loss: 0.7407 - accuracy: 0.5996
Epoch 10/40
161/161 [==============================] - 1s 3ms/step - loss: 0.7390 - accuracy: 0.5993

In [64]:
# Predicting the Test set results
y_pred = ann.predict(X_test)

print(y_pred)

y_pred_class = y_pred.argmax(axis=1)
print()
print(y_pred_class)


81/81 [==============================] - 0s 3ms/step
[[7.4835807e-01 1.4777622e-01 1.0386566e-01]
 [7.6902052e-04 5.2567554e-01 4.7355545e-01]
 [1.3731534e-03 5.2988476e-01 4.6874213e-01]
 ...
 [7.4835807e-01 1.4777622e-01 1.0386566e-01]
 [7.4909702e-03 5.3921026e-01 4.5329872e-01]
 [5.3851766e-04 5.2324283e-01 4.7621873e-01]]

[0 1 1 ... 0 1 1]


In [51]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred_class))

0.9937621832358674


In [52]:
test = ann.predict(sc.transform([[3.5426830286659757e-06,0.24547880116959062,0.3226955560075358]]))
print(test.argmax(axis=1))

1/1 [==============================] - 0s 41ms/step
[0]


In [53]:
test = ann.predict(sc.transform([[8.925958444735739e-06,0.4325036549707602,0.3262577476893473]]))
print(test.argmax(axis=1))

1/1 [==============================] - 0s 37ms/step
[0]


In [54]:
test = ann.predict(sc.transform([[9.90156822887783e-06,0.12960745614035085,0.2034841174904795]]))
print(test)
print(test.argmax(axis=1))

1/1 [==============================] - 0s 34ms/step
[[1.0000000e+00 1.8940977e-26 4.3107651e-14]]
[0]
