In [ ]:
# Artificial Neural Network
# Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf

2023-10-27 14:37:30.110348: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
tf.__version__

'2.14.0'

In [ ]:
# Part 1 - Data Preprocessing
# Importing the dataset
dataset = pd.read_csv('new_normalized_output.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[1.19573174e-05 5.06454678e-01 3.46215783e-01]
 [1.01628923e-05 5.02067251e-01 3.46215783e-01]
 [7.67160301e-06 4.93486111e-01 3.46215783e-01]
 ...
 [3.42073181e-06 1.30027047e-01 4.60889086e-01]
 [3.68205585e-06 1.30029971e-01 4.60889086e-01]
 [3.97822311e-06 1.30018275e-01 4.60401114e-01]]
['anodic' 'anodic' 'anodic' ... 'corrosion' 'corrosion' 'corrosion']


In [ ]:
# Encoding categorical data
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 ... 2 2 2]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

In [ ]:
print(X_train, y_train)

[[3.42073181e-06 1.30040205e-01 3.97452789e-01]
 [1.19050526e-05 1.29578947e-01 2.27736302e-01]
 [2.30574920e-06 1.30438596e-01 7.88171574e-01]
 ...
 [4.67508724e-06 1.29668129e-01 1.38291123e-01]
 [5.42421618e-06 1.30043129e-01 3.98575126e-01]
 [2.47996523e-06 1.29652778e-01 1.87039478e-01]] [2 1 0 ... 1 2 1]


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Part 2 - Building the ANN
# Initializing the ANN
ann = tf.keras.models.Sequential()
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='softmax'))

In [ ]:
# Example of adding dropout layers
ann.add(tf.keras.layers.Dropout(0.5))

In [ ]:
# Part 3 - Training the ANN
# Compiling the ANN
ann.compile(optimizer = 'FTRL', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
# Training the ANN on the Training set
history=ann.fit(X_train, y_train, batch_size = 32, epochs = 10)


Epoch 1/10
56877/56877 [==============================] - 78s 1ms/step - loss: 7.7092 - accuracy: 0.3440
Epoch 2/10
56877/56877 [==============================] - 78s 1ms/step - loss: 7.7133 - accuracy: 0.3439
Epoch 3/10
56877/56877 [==============================] - 78s 1ms/step - loss: 7.6982 - accuracy: 0.3440
Epoch 4/10
56877/56877 [==============================] - 79s 1ms/step - loss: 7.6931 - accuracy: 0.3441
Epoch 5/10
56877/56877 [==============================] - 80s 1ms/step - loss: 7.7007 - accuracy: 0.3440
Epoch 6/10
56877/56877 [==============================] - 80s 1ms/step - loss: 7.7205 - accuracy: 0.3441
Epoch 7/10
56877/56877 [==============================] - 88s 2ms/step - loss: 7.7215 - accuracy: 0.3438
Epoch 8/10
56877/56877 [==============================] - 162s 3ms/step - loss: 7.7075 - accuracy: 0.3443
Epoch 9/10
56877/56877 [==============================] - 80s 1ms/step - loss: 7.7019 - accuracy: 0.3439
Epoch 10/10
56877/56877 [=============================

In [ ]:
# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred)
print(ann.predict(sc.transform([[3.5426830286659757e-06,0.24547880116959062,0.3226955560075358]])))


1/1 [==============================] - 0s 18ms/step
[[1.]]
