In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

tf.__version__

# Part 1 - Data Preprocessing
# Importing the dataset
dataset = pd.read_csv('new_normalized_output.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[6.01902098e-05 1.00000000e+00 3.12591682e-01]
 [6.95178276e-05 5.48676711e-01 3.14064430e-01]
 [5.98924965e-05 3.91313184e-01 3.18715504e-01]
 ...
 [3.81637043e-05 6.91692476e-02 7.13452354e-04]
 [8.24844739e-05 6.91438305e-02 6.58572104e-04]
 [1.27110904e-04 6.91438305e-02 0.00000000e+00]]
['anodic' 'anodic' 'anodic' ... 'corrosion' 'corrosion' 'corrosion']


In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 ... 2 2 2]


In [22]:
from sklearn.neural_network import MLPClassifier
clf=MLPClassifier(solver='lbfgs',alpha=1e-5,hidden_layer_sizes=(5,2),random_state=1)
clf.fit(X,y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [23]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Assuming you have your data in X (features) and y (target labels)
# X should be your feature matrix, and y should be your target labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create an MLPClassifier with specified parameters
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)

# Train (fit) the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the classifier's performance, for example, by calculating accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.3294437961882536


In [20]:
print(y_pred)

[2 2 2 ... 2 2 2]


In [21]:
print(X_test)

[[8.52269197e-04 7.95545335e-02 2.44766624e-01]
 [5.89259493e-05 1.89852073e-01 3.21829849e-01]
 [1.29109444e-04 7.59782193e-02 1.80260022e-01]
 ...
 [1.53370333e-04 7.69476064e-02 4.63858156e-01]
 [1.44410378e-04 7.56286671e-02 2.08147518e-01]
 [6.42288641e-05 8.23142047e-02 4.62520570e-01]]
